name: Votifier
main: com.vexsoftware.votifier.Votifier
version: ${project.version}
description: A plugin that gets notified when votes are made for the server on toplists.
api-version: 1.15
authors: [blakeman8192, Kramer]